resolver: lts-15.11
extra-deps:
- git: https://github.com/jgm/pandoc-types
  commit: dd50a6eaeaf63773bbf04d6ef34b86d6f92b7825
ghc-options:
   "$locals": -fhide-source-paths
packages:
- commonmark
- commonmark-extensions
- commonmark-pandoc
- commonmark-cli
# These next two lines are needed to use
# stack build --profile --ghc-options="-fno-prof-auto"
# apply-ghc-options: everything
# rebuild-ghc-options: true
