resolver: lts-14.6
extra-deps:
- emojis-0.1
- git: https://github.com/jgm/pandoc-types
  commit: 4acb0e50f10d8f41f94c0973384d63f06d0b9ffd
ghc-options:
   "$locals": -fhide-source-paths
packages:
- commonmark
- commonmark-extensions
- commonmark-pandoc
- commonmark-cli
# These next two lines are needed to use
# stack build --profile --ghc-options="-fno-prof-auto"
# apply-ghc-options: everything
# rebuild-ghc-options: true
